"""track agent transaction timestamps

Revision ID: 089e0eb2feef
Revises: e322993952a9
Create Date: 2026-09-04 02:25:02.857432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089e0eb2feef'
down_revision: Union[str, Sequence[str], None] = 'e322993952a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_reputation', sa.Column('last_transaction_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_reputation', 'last_transaction_at')
    # ### end Alembic commands ###
