"""create commerce persistence schema

Revision ID: 1843be6e0b22
Revises: 
Create Date: 2026-09-04 01:37:40.461576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1843be6e0b22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('merchant_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_agents_merchant_id'), 'agents', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_agents_role'), 'agents', ['role'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_table('merchants',
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('razorpay_account_reference', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('agent_reputation',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('successful_transactions', sa.Integer(), nullable=False),
    sa.Column('review_transactions', sa.Integer(), nullable=False),
    sa.Column('blocked_transactions', sa.Integer(), nullable=False),
    sa.Column('policy_violations', sa.Integer(), nullable=False),
    sa.Column('last_violation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('catalog_items',
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('item_name', sa.String(length=300), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_catalog_items_merchant_id'), 'catalog_items', ['merchant_id'], unique=False)
    op.create_table('negotiations',
    sa.Column('negotiation_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_agent_id', sa.String(length=128), nullable=False),
    sa.Column('merchant_agent_id', sa.String(length=128), nullable=False),
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('proposal_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.item_id'], ),
    sa.ForeignKeyConstraint(['merchant_agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('negotiation_id')
    )
    op.create_index(op.f('ix_negotiations_buyer_agent_id'), 'negotiations', ['buyer_agent_id'], unique=False)
    op.create_index(op.f('ix_negotiations_item_id'), 'negotiations', ['item_id'], unique=False)
    op.create_index(op.f('ix_negotiations_merchant_agent_id'), 'negotiations', ['merchant_agent_id'], unique=False)
    op.create_index(op.f('ix_negotiations_status'), 'negotiations', ['status'], unique=False)
    op.create_table('negotiation_messages',
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('negotiation_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('proposed_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.negotiation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_negotiation_messages_agent_id'), 'negotiation_messages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_negotiation_messages_negotiation_id'), 'negotiation_messages', ['negotiation_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('negotiation_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_agent_id', sa.String(length=128), nullable=False),
    sa.Column('merchant_agent_id', sa.String(length=128), nullable=False),
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('requested_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('authorized_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=200), nullable=True),
    sa.Column('fallback_payment_url', sa.String(length=2000), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('policy_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.item_id'], ),
    sa.ForeignKeyConstraint(['merchant_agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.negotiation_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_buyer_agent_id'), 'transactions', ['buyer_agent_id'], unique=False)
    op.create_index('ix_transactions_buyer_created', 'transactions', ['buyer_agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_transactions_item_id'), 'transactions', ['item_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_agent_id'), 'transactions', ['merchant_agent_id'], unique=False)
    op.create_index('ix_transactions_merchant_created', 'transactions', ['merchant_agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_negotiation_id'), 'transactions', ['negotiation_id'], unique=False)
    op.create_index(op.f('ix_transactions_razorpay_order_id'), 'transactions', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('decision_id', sa.String(length=128), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('observed_value', sa.String(length=500), nullable=True),
    sa.Column('allowed_value', sa.String(length=500), nullable=True),
    sa.Column('risk_contribution', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_policy_decisions_rule_code'), 'policy_decisions', ['rule_code'], unique=False)
    op.create_index(op.f('ix_policy_decisions_transaction_id'), 'policy_decisions', ['transaction_id'], unique=False)
    op.create_table('price_observations',
    sa.Column('observation_id', sa.String(length=128), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_agent_id', sa.String(length=128), nullable=False),
    sa.Column('merchant_agent_id', sa.String(length=128), nullable=False),
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('agreed_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.item_id'], ),
    sa.ForeignKeyConstraint(['merchant_agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_index(op.f('ix_price_observations_buyer_agent_id'), 'price_observations', ['buyer_agent_id'], unique=False)
    op.create_index(op.f('ix_price_observations_item_id'), 'price_observations', ['item_id'], unique=False)
    op.create_index(op.f('ix_price_observations_merchant_agent_id'), 'price_observations', ['merchant_agent_id'], unique=False)
    op.create_index(op.f('ix_price_observations_observed_at'), 'price_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_price_observations_transaction_id'), 'price_observations', ['transaction_id'], unique=False)
    op.create_index('ix_price_pair_time', 'price_observations', ['buyer_agent_id', 'merchant_agent_id', 'observed_at'], unique=False)
    op.create_table('transaction_events',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_transaction_events_created_at'), 'transaction_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_transaction_events_event_type'), 'transaction_events', ['event_type'], unique=False)
    op.create_index('ix_transaction_events_order', 'transaction_events', ['transaction_id', 'sequence_number'], unique=False)
    op.create_index(op.f('ix_transaction_events_transaction_id'), 'transaction_events', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_events_transaction_id'), table_name='transaction_events')
    op.drop_index('ix_transaction_events_order', table_name='transaction_events')
    op.drop_index(op.f('ix_transaction_events_event_type'), table_name='transaction_events')
    op.drop_index(op.f('ix_transaction_events_created_at'), table_name='transaction_events')
    op.drop_table('transaction_events')
    op.drop_index('ix_price_pair_time', table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_transaction_id'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_observed_at'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_merchant_agent_id'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_item_id'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_buyer_agent_id'), table_name='price_observations')
    op.drop_table('price_observations')
    op.drop_index(op.f('ix_policy_decisions_transaction_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_rule_code'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_razorpay_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_negotiation_id'), table_name='transactions')
    op.drop_index('ix_transactions_merchant_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_agent_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_item_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index('ix_transactions_buyer_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_buyer_agent_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_negotiation_messages_negotiation_id'), table_name='negotiation_messages')
    op.drop_index(op.f('ix_negotiation_messages_agent_id'), table_name='negotiation_messages')
    op.drop_table('negotiation_messages')
    op.drop_index(op.f('ix_negotiations_status'), table_name='negotiations')
    op.drop_index(op.f('ix_negotiations_merchant_agent_id'), table_name='negotiations')
    op.drop_index(op.f('ix_negotiations_item_id'), table_name='negotiations')
    op.drop_index(op.f('ix_negotiations_buyer_agent_id'), table_name='negotiations')
    op.drop_table('negotiations')
    op.drop_index(op.f('ix_catalog_items_merchant_id'), table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_table('agent_reputation')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_role'), table_name='agents')
    op.drop_index(op.f('ix_agents_merchant_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
