"""add cryptographic ledger blocks

Revision ID: 84d5b51dc2b1
Revises: 089e0eb2feef
Create Date: 2026-09-04 07:48:02.217234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d5b51dc2b1'
down_revision: Union[str, Sequence[str], None] = '089e0eb2feef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_blocks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('signer_public_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_blocks_block_hash'), 'ledger_blocks', ['block_hash'], unique=True)
    op.create_index(op.f('ix_ledger_blocks_event_type'), 'ledger_blocks', ['event_type'], unique=False)
    op.create_index(op.f('ix_ledger_blocks_sequence_number'), 'ledger_blocks', ['sequence_number'], unique=True)
    op.create_index(op.f('ix_ledger_blocks_transaction_id'), 'ledger_blocks', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_blocks_transaction_id'), table_name='ledger_blocks')
    op.drop_index(op.f('ix_ledger_blocks_sequence_number'), table_name='ledger_blocks')
    op.drop_index(op.f('ix_ledger_blocks_event_type'), table_name='ledger_blocks')
    op.drop_index(op.f('ix_ledger_blocks_block_hash'), table_name='ledger_blocks')
    op.drop_table('ledger_blocks')
    # ### end Alembic commands ###
