"""enforce transaction event sequence uniqueness

Revision ID: e322993952a9
Revises: 1843be6e0b22
Create Date: 2026-09-04 02:14:04.187733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e322993952a9'
down_revision: Union[str, Sequence[str], None] = '1843be6e0b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_events_order'), table_name='transaction_events')
    op.create_index(op.f('ix_transaction_events_actor_id'), 'transaction_events', ['actor_id'], unique=False)
    op.create_index('ix_transaction_events_transaction_sequence', 'transaction_events', ['transaction_id', 'sequence_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_events_transaction_sequence', table_name='transaction_events')
    op.drop_index(op.f('ix_transaction_events_actor_id'), table_name='transaction_events')
    op.create_index(op.f('ix_transaction_events_order'), 'transaction_events', ['transaction_id', 'sequence_number'], unique=False)
    # ### end Alembic commands ###
